### PR TITLE
support android build

### PR DESCRIPTION
**Pull request by aydinkim**
Support android build
This commit does not affect to each submodule's original standalone build system.

### CODE REVIEW

**Comment by metajack** [comment]
I think this is the wrong way to handle this. We shouldn't be exporting these, but passing them. Also, it would be good if these new android variables were overridable so that they can be controlled from the top level.

**Comment by aydinkim** [comment]
Okay, I can try to fix this.

**Comment by aydinkim** [comment]
According to your guidance, I have submitted new PR.
Plz check that.
Thank you.

**Comment by aydinkim** [comment]
Merge with another PR. Close.

**Pull request closed without merging**
